using System.Text;
using BombiHighSchool.App.Models;

namespace BombiHighSchool.App.Services;

public sealed class TranscriptExportService
{
    public string BuildText(Student student, StudentDetails details, IReadOnlyList<TranscriptRow> rows)
    {
        var sb = new StringBuilder();
        sb.AppendLine("BOMBI HIGH SCHOOL");
        sb.AppendLine("ACADEMIC TRANSCRIPT");
        sb.AppendLine(new string('=', 72));
        sb.AppendLine($"Student: {student.Name}");
        sb.AppendLine($"BHS ID: {student.Id}");
        sb.AppendLine($"Class: {student.ClassLevel} {details.Arm}".Trim());
        sb.AppendLine($"Department: {details.Department}");
        sb.AppendLine();
        sb.AppendLine($"{"Subject",-28} {"CA",5} {"Exam",6} {"Total",7} {"Grade",6}");
        sb.AppendLine(new string('-', 58));
        foreach (var row in rows)
            sb.AppendLine($"{row.Subject[..Math.Min(28, row.Subject.Length)],-28} {row.CA,5:0.#} {row.Exam,6:0.#} {row.Total,7:0.#} {row.Grade,6}");
        sb.AppendLine();
        sb.AppendLine($"Average: {(rows.Count == 0 ? 0 : rows.Average(x => x.Total)):0.00}%");
        sb.AppendLine();
        sb.AppendLine("Generated by Bombi High School Windows App.");
        return sb.ToString();
    }
}
